### ISSUE TITLE
Saved projects don't load correctly

### ISSUE THREAD

**Issue by tobias47n9e** [innstereo/innstereo#76]
Longer projects with many subfolders can cause this traceback when loading the saved project file:

```
Traceback (most recent call last):
  File "/innstereo/innstereo/dialog_windows.py", line 729, in on_button_confirm_open_clicked
    self.open_project(json_file)
  File "/innstereo/innstereo/main_ui.py", line 871, in open_project
    self.add_feature(lyr_dict["type"], lyr_store, f[0], f[1], f[2], f[3], f[4])
IndexError: list index out of range
```

**Comment by tobias47n9e** [comment]
The problem actually happens during saving. The faultplane layers have more columns and are cut off at 3 columns.
